## M. Amintoosi
## کاوش الگوهای پرتکرار
استخراج قوانین انجمنی

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
cd /content/drive/My Drive/colabs/CoWork/Kohan

/content/drive/My Drive/colabs/CoWork/Kohan


In [3]:
import pandas as pd
import numpy as np

# df = pd.read_excel(r'matrix20.xlsx') 
df = pd.read_excel(r'data/403.xlsx') 
# print (df)
metabolitNames = df.head(0).to_string()

In [4]:
metabolitNames

'Empty DataFrame\nColumns: [Acacia farnesiana, Acacia seyal, Acer rubrum, Acer saccharum, Achillea millefolium, Achillea santolina, Achillea wilhelmsii, Aconitum coreanum, Acorus calamus, Acronychia pedunculata, Actaea racemosa, Aegiceras corniculatum, Agave americana, Aglaia elliptica , Agrimonia pilosa , Ailanthus altissima, Ajuga chia, Alangium salviifolium, Albizia adianthifolia, Albizia amara, Albizia lebbeck, Albizia zygia, Alchornea cordifolia, Allium ascalonicum, Allium cepa, Allium macrostemon, Allium sativum, Aloe vera, Alpinia galangal, Alpinia sp., Amoora aphanamimixis, Andrographis paniculata, Angelica sinensis, Annona montana, Annona muricata, Annona purpurea, Annona squamosa, Anoectochilus formosanus, Anthemis mirheydari, Antidesma bunius, Arabidopsis thaliana, Arachis hypogaea, Arctium lappa, Ardisia colorata, Ardisia crispa, Areca catechu, Argania spinosa, Aristolochia baetica, Artemisia absinthium, Artemisia annua, Artemisia biennis, Artemisia californica, Artemisia d

In [5]:
numpy_matrix = df.values
d =  numpy_matrix.transpose()
T = [[str(i)[3:] for i in row ] for row in d]
T = [[int(i) for i in row if i != ''] for row in T]
# T[0][:20]

In [6]:
# x = [row[~np.isnan(row)] for row in T]

In [7]:
# print(T.shape)
# print(type(T))
T[0:3]

[[1036, 2647, 5548, 5872, 8210, 8817, 13297, 13867, 13974, 14320, 46784],
 [2647, 5548, 8817],
 [1411, 2647, 6798, 30222, 30754, 38195]]

In [8]:
# !pip3 install Orange3-Associate

In [9]:
from orangecontrib.associate.fpgrowth import *

In [10]:
%%time
minFreq = 10
itemsets = frequent_itemsets(T, minFreq)

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 10.3 µs


In [12]:
item = next(itemsets)
item
# len(list(itemsets))
# با یک بار مراجعه به آن خالی می‌شود!!!

(frozenset({3672}), 61)

In [ ]:
freqIS = list(itemsets)

In [ ]:
len(freqIS)
# تعداد فایل از این کمتر است به این دلیل که یک دانه‌ای ها را نمایش نمی دهیم

In [ ]:
# freqIS

In [ ]:
# k=1
# n = 1
# while True:
#     print("======= sets with %d elements ======="% k)
#     flag = True
#     for i in range(len(freqIS)):
#         set_i = freqIS[i][0]
#         if(len(set_i)==k):
#             flag = False
#             items = [x for x in set_i]
#             print(n,items,freqIS[i][1])
#             n = n+1
#     if flag:
#         break
#     k = k+1

In [ ]:
# fileName = str(minFreq)+"_common_metabolite_set_number_order"+".txt"
# output = open(fileName, 'w')
# k = 1
# n = 1
# while True:
#     output.write("======= sets with %d elements =======\n"% k)
#     flag = True
#     for i in range(len(freqIS)):
#         set_i = freqIS[i][0]
#         if(len(set_i)==k):
#             flag = False
#             items = [x for x in set_i]
#             output.write("%d %s %d\n" % (n,items,freqIS[i][1]))
#             n = n+1
#     if flag:
#         break
#     k = k+1
# output.close() 

In [ ]:
itemSetNo = [None] * len(freqIS)
for i in range(len(freqIS)):
    itemSetNo[i] = len(freqIS[i][0])

fileName = str(minFreq)+"_common_metabolite_set_number_order"+".txt"
output = open(fileName, 'w')
n = 1
prevSetNo = -1
for k in range(max(itemSetNo)):
    nSetNo = k+1
    for i in range(len(freqIS)):
        set_i = freqIS[i][0]
        thisSetNo = len(set_i)
        if(thisSetNo==nSetNo and prevSetNo != thisSetNo):
            output.write("======= sets with %d elements =======\n"% nSetNo)
        if(thisSetNo==nSetNo):
            items = [x for x in set_i]
            output.write("%d %s %d\n" % (n,items,freqIS[i][1]))
            n = n+1
            prevSetNo = thisSetNo
output.close() 

In [ ]:
itemFreq = [None] * len(freqIS)
for i in range(len(freqIS)):
    itemFreq[i] = freqIS[i][1]

fileName = str(minFreq)+"_common_metabolite_freq_number_order"+".txt"
output = open(fileName, 'w')
n = 1
prevFreq = -1
for k in range(max(itemFreq)):
    nFreq = k+1
    for i in range(len(freqIS)):
        set_i = freqIS[i][0]
        thisFreq = freqIS[i][1]
        if(thisFreq==nFreq and prevFreq != thisFreq):
            output.write("======= sets with frequency=%d =======\n"% nFreq)
        if(thisFreq==nFreq):
            items = [x for x in set_i]
            output.write("%d %s\n" % (n,items))
            n = n+1
            prevFreq = thisFreq
output.close() 

In [ ]:
items = freqIS[i][0]
items

frozenset({26092})

In [ ]:
for x in items:
    print(x)

26092


In [ ]:
lst = [x for x in items]

In [ ]:
print('\n'.join('{} {}'.format(*k) for k in enumerate(lst)))

0 26092


In [ ]:
itemFreq = [None] * len(freqIS)
for i in range(len(freqIS)):
    itemFreq[i] = freqIS[i][1]
max(itemFreq)

61

In [ ]:
# for i in range(max(itemFreq)):
#     print(i)

In [ ]:
max(T[0])

46784

In [ ]:
# from sklearn.feature_extraction.text import HashingVectorizer
# from sklearn.feature_extraction.text import FeatureHasher
# hasher = FeatureHasher(input_type='string')
# X = hasher.transform(corpus)

In [ ]:
# listToStr = ' '.join([str(elem) for elem in T[0]]) 
# print(listToStr)  
# listToStr

1036 2647 5548 5872 8210 8817 13297 13867 13974 14320 46784


'1036 2647 5548 5872 8210 8817 13297 13867 13974 14320 46784'

In [ ]:
corpus = [None] * len(T)
for i in range(len(T)):
    listToStr = ' '.join([str(elem) for elem in T[i]]) 
    corpus[i] = listToStr

In [ ]:
type(corpus)

list

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(token_pattern = r"(?u)\b\w+\b")
X = vectorizer.fit_transform(corpus)
print(X.shape)
print(X.toarray())

(403, 7416)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(X[27])

  (0, 5694)	1
  (0, 5572)	1
  (0, 5499)	1
  (0, 4651)	1
  (0, 4649)	1
  (0, 4608)	1
  (0, 4605)	1
  (0, 4604)	1
  (0, 4603)	1
  (0, 798)	1
  (0, 6475)	1
  (0, 6429)	1
  (0, 2344)	1
  (0, 2341)	1
  (0, 492)	1
  (0, 481)	1
  (0, 457)	1
  (0, 414)	1
  (0, 5982)	1
  (0, 1079)	1
  (0, 5913)	1
  (0, 313)	1


In [ ]:
bow = X.toarray()
print(bow[0] & bow[2])
print(sum(bow[0] & bow[2]))

[0 0 0 ... 0 0 0]
1


In [ ]:
print((corpus[24]))
print(len(T[24]))
print((len(corpus[24].split())))
row24 = X[24,:].toarray()
print(sum(sum(row24)))
print(sum(bow[24,:]))
# print(bow[24,:])

1 4 8 9 12 15 20 34 44 51 218 747 1242 1243 1245 1246 1266 1267 1336 1389 1495 2374 2378 2665 2689 2743 2776 4631 5152 5231 5374 5387 5436 5438 5464 5466 5486 5561 6654 6659 6669 6679 6804 6866 11093 11094 14773 14775 19064 29547 30753 32012 34232 34649 38408 38666 40074 50680 51720
59
59
59
59


In [ ]:
featureNames = vectorizer.get_feature_names()
type(featureNames)

list

In [ ]:
featureNames.index("9")

7103

In [ ]:
list(items)

[4, 20]

In [ ]:
commItems_idx = [featureNames.index(str(x)) for x in list(items)]
print(commItems_idx)

[4347, 1439]


In [ ]:
itemFreq = [None] * len(freqIS)
for i in range(len(freqIS)):
    itemFreq[i] = freqIS[i][1]

G = [] # empty graph    
    
fileName = str(minFreq)+"_common_metabolite_freq"+".txt"
output = open(fileName, 'w')
n = 1
prevFreq = -1
for k in range(max(itemFreq)):
    nFreq = k+1
    for i in range(len(freqIS)):
        set_i = freqIS[i][0]
        thisFreq = freqIS[i][1]
        if(thisFreq==nFreq and prevFreq != thisFreq):
            output.write("======= sets with frequency=%d =======\n"% nFreq)
        if(thisFreq==nFreq):
            items = [x for x in set_i]
            commItems_idx = [featureNames.index(str(x)) for x in list(items)]
#             print(commItems_idx)
            metabolits_list = [featureNames[int(ii)] for ii in commItems_idx]
            output.write("%d %s --" % (n,metabolits_list))
            
            vec = np.zeros((len(bow[0]),), dtype=int)
            vec[commItems_idx] = 1;
            commItems = []
            for j in range(len(bow)):
                row = bow[j]
                if sum(row&vec)!=0:
                    commItems.append(j)
                    
# #          commItems = [rowIdx for row in bow if sum(row&vec)!=0]
            output.write(" %s \n" % (commItems))
    
#             col_list = [metabolitNames[int(ii)] for ii in commItems]
#             output.write(" %s \n" % (col_list))
        
            n = n+1
            prevFreq = thisFreq
output.close() 

In [ ]:
print(set_i)
print(items)
print(commItems_idx)
print(featureNames.index('2374'))

frozenset({4, 20})
[4, 20]
[6988, 2802]
1830


In [ ]:
featureNames

In [ ]:
vec = np.zeros((len(bow[0]),), dtype=int)
vec.shape

(7409,)

In [ ]:
T[32]

In [ ]:
G = np.zeros([5,5])
a = [1,3]
G[a,a] = 1
G

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
b = a[::-1]
print(b)

[3, 1]
